version: '3.8'

services:
  wave-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1155:1155"
    environment:
      - PORT=1155
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"